[package]
name = "merge-types"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.6.0"
swc_common = "5.0.0"
swc_ecma_ast = "5.0.0"
swc_ecma_codegen = "5.0.0"
swc_ecma_parser = "6.0.0"
