// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Schedule } from './Schedule';

export type AppConfig = {
    gas_url: string | null;
    formatter: [string, string][];
    current_formatter: string;
    schedules: Array<Schedule>;
    advanced: boolean;
};
