name: 'publish'
on:
    push:
        branches:
            - main
        tags:
            - 'v*'
jobs:
    publish-tauri:
        permissions: write-all
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
            - name: install frontend dependencies
              run: bun install
            - name: Install Python
              uses: actions/setup-python@v2
            - name: Restore mtime
              run: python ./git-restore-mtime.py

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      src-tauri/target
                  key: ${{ runner.os }}-cargo
            - uses: tauri-apps/tauri-action@v0
              env:
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD}}
                  TAURI_SIGNING_PRIVATE_KEY: ${{secrets.TAURI_SIGNING_PRIVATE_KEY}}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: app-v__VERSION__
                  releaseName: 'App v__VERSION__'
                  releaseBody: 'See the assets to download this version and install.'
                  releaseDraft: true
                  prerelease: false
